### ISSUE TITLE
Merge upstream

### ISSUE THREAD

**Issue by mart-e** [Arthur-Milchior/anki#3]
Hello,

Thank yu for your valuable work helping to understand the Anki code.
Have you tried reaching the upstream project to see if it can be included? I think it would benefit the whole project.
I may miss part of the story though.

**Comment by Arthur-Milchior** [comment]
You're welcome.
I tried in 2017. I'll let you read the discussion by yourself https://anki.tenderapp.com/discussions/ankidesktop/25532-comments-in-code
Of course, you're free to tell him your point of view, and see whether he may change his mind. I won't try.

However, I must state that Damien Elmes did merge some of my work in anki. I did correct a few bugs(Actually, there are bugs in anki which I did correct bug which remains in the last stable version of anki, because DAE did not update any new version since I did those correction). But that's unrelated to comments.

**Comment by mart-e** [comment]
Ok too bad...
